#!/bin/bash

docker run \
    --net host \
    -u $UID:`id -g` \
    -e DISPLAY=$DISPLAY \
    -v $HOME/.Xauthority:/root/.Xauthority \
    -v `pwd`:/workdir \
    -it --rm tak0kada/python-docker-env \
    ipython $@
